name: "Release Lumineria Launcher"

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build and Release Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__
          releaseName: 'Lumineria Launcher v__VERSION__'
          releaseBody: 'Nueva versión del launcher.'
          releaseDraft: false
          prerelease: false

  build-flatpak:
    runs-on: ubuntu-latest
    needs: build-tauri
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Construir el paquete Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: lumineria-launcher.flatpak
          manifest-path: org.lumineria.Launcher.yml
          cache-key: flatpak-builder-${{ github.sha }}

      - name: Subir Flatpak al Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} lumineria-launcher.flatpak